name: "Initialize"
description: "Install npm dependencies"

inputs:
  artifactoryEmail:
    required: true
  artifactoryUsername:
    required: true
  artifactoryPassword:
    required: true

outputs:
  node-version:
    description: "Installed node.js version"
    value: ${{ steps.node-version.outputs.node-version }}

runs:
  using: "composite"
  steps:
    - name: Read NodeJS version from .nvmrc
      id: node-version
      shell: bash
      run: echo "node-version=$(cat .nvmrc | tr -d '[:space:]')" >> $GITHUB_OUTPUT

    - uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.node-version.outputs.node-version }}

    - uses: actions/cache@v3
      id: nodemodules-cache
      with:
        path: |
          node_modules
          packages/front/node_modules
          packages/back/node_modules
        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: steps.nodemodules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: npm install --include=dev
