name: After test

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "${{ toJSON( github )}}" >> $GITHUB_STEP_SUMMARY
