name: After test

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  something:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          cat >> $GITHUB_STEP_SUMMARY << EOF
          \`\`\`
          ${{ toJSON(github) }}
          \`\`\`
          EOF
