name: After test

on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

env:
  sha: ${{ github.sha }}
  branch: ${{ github.event.workflow_run.head_branch }}

jobs:
  something:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "branch: ${{ env.branch }}"
          echo "sha: ${{env.sha }}"
