name: After deploy

on:
  workflow_run:
    workflows: [Deploy]
    types:
      - completed

jobs:
  after-deploy:
    name: Do something after deploy
    runs-on: ubuntu-latest
    steps:
      - name: Do it
        run: |
          echo "```${{ toJSON(github) }}```" >> $GITHUB_STEP_SUMMARY
          echo "```${{ github.event.workflow_run }}```" >> $GITHUB_STEP_SUMMARY
