name: Backend - Deploy

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      targetEnv:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy ${{ inputs.image }} to ${{ inputs.targetEnv }}!" >> $GITHUB_STEP_SUMMARY
