name: Backend - Deploy

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      targetEnv:
        required: true
        type: string
      accessKeyIdSecretKey:
        required: true
        type: string
      secretAccessKeySecretKey:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy backend
    runs-on: ubuntu-latest
    env:
      ECS_CLUSTER_NAME: vrfi-cluster
      service: vrfi-backend-v6-${{ inputs.targetEnv }}

    steps:
      - name: Configure AWS credentials to environment
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets[inputs.accessKeyIdSecretKey] }}
          aws-secret-access-key: ${{ secrets[inputs.secretAccessKeySecretKey] }}
          aws-region: eu-west-1
          mask-aws-account-id: false

      - name: Download ECS task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.service }} --query taskDefinition > ecs-task-definition.json
          cat ecs-task-definition.json | jq '.|del(.containerDefinitions[].repositoryCredentials)' > ecs-task-definition-ecr.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ecs-task-definition-ecr.json
          container-name: ${{ env.service }}
          image: ${{ inputs.image }}

      - name: Deploy to Amazon ECS service
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.render-task-def.outputs.task-definition }}
          service: ${{ env.service }}
          cluster: ${{ env.ECS_CLUSTER_NAME }}
          wait-for-service-stability: true
