name: Backend - Build

on:
  workflow_call:
    inputs:
      targetEnv:
        required: true
        type: string
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - id: image
        name: Image
        run: |
          echo "image=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          echo "Build ${{ steps.image.outputs.image }} to ${{ inputs.targetEnv }}" >> $GITHUB_STEP_SUMMARY
