name: Backend - Build

on:
  workflow_call:
    inputs:
      targetEnv:
        required: true
        type: string
    outputs:
      image:
        value: ${{ jobs.build.outputs.image }}

jobs:
  build:
    name: Build backend
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - id: image
        name: Image
        run: |
          echo "image=${{ github.ref }}" >> $GITHUB_OUTPUT

      - name: Build
        run: |
          echo "Build ${{ steps.image.outputs.image }} with ${{ inputs.targetEnv }}"

      - name: Add summary
        uses: actions/github-script@v6
        with:
          script: |
            await core.summary
              .addHeading('Image')
              .addCodeBlock('${{ steps.image.outputs.image }}')
              .write();
