name: Content deploy
run-name: |
  Content deploy: ${{ github.event.client_payload.env || 'test' }}

on:
  repository_dispatch:
    types: [content-build]

concurrency:
  group: content-deploy-${{ github.event.client_payload.env || 'test' }}

env:
  env: ${{ github.event.client_payload.env || 'test' }}

jobs:
  validate-env:
    name: Validate target environment
    runs-on: ubuntu-latest
    outputs:
      deployAll: ${{ steps.validate.outputs.deployAll }}
    steps:
      - name: Validate "${{ env.env }}"
        id: validate
        uses: actions/github-script@v6
        with:
          script: |
            if (['prod', 'staging'].includes('${{ env.env }}')) {
              core.setOutput('deployAll', 'false');
              return;
            }

            if (['test', 'dev', 'preview'].includes('${{ env.env }}')) {
              core.setOutput('deployAll', 'true');
              return;
            }

            core.setFailed('Invalid env: ${{ env.env }}');

  deploy-changes:
    needs: [validate-env]
    name: Deploy changes
    uses: ./.github/workflows/deploy-changes.yml
    if: success() && needs.validate-env.outputs.deployAll == 'true'
    secrets: inherit
    with:
      env: ${{ github.event.client_payload.env || 'test' }}

  front-build:
    name: Build frontend (prod/staging)
    needs: [validate-env]
    uses: ./.github/workflows/front-build.yml
    if: success() && needs.validate-env.outputs.deployAll == 'false'
    secrets: inherit
    with:
      ref: environment-${{ github.event.client_payload.env || 'test' }}
      targetEnv: ${{ github.event.client_payload.env || 'test' }}

  front-deploy:
    name: Deploy frontend (prod/staging)
    needs: [validate-env, front-build]
    uses: ./.github/workflows/front-deploy.yml
    if: success() && needs.validate-env.outputs.deployAll == 'false'
    secrets: inherit
    with:
      targetEnv: ${{ github.event.client_payload.env || 'test' }}
