name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: packages/back/**

      - run: |
          echo "${{ steps.changes.outputs }}"
