name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes
        id: changes
        uses: tj-actions/changed-files@v35
        with:
          files: packages/*
          dir_names: true
          dir_names_max_depth: 2
          # base_sha: koira

      - name: Debug
        run: |
          echo "${{ steps.changes.outputs.all_changed_files }}";
          echo "back changed: ${{ contains(steps.changes.outputs.all_changed_files, 'packages/back') }}"
          echo "front changed: ${{ contains(steps.changes.outputs.all_changed_files, 'packages/front') }}"
