name: Deploy

on:
  push:
    branches:
      - main

jobs:
  check-for-changes:
    name: Check for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check for changes
        if: failure()
        id: changes
        uses: tj-actions/changed-files@v35
        continue-on-error: true
        with:
          files: packages/*
          dir_names: true
          dir_names_max_depth: 2

      - name: Debug
        run: |
          echo "errr: ${{ toJSON(steps.changes) }}" >> $GITHUB_STEP_SUMMARY
          echo "all_changed_files: ${{ steps.changes.outputs.all_changed_files }}" >> $GITHUB_STEP_SUMMARY
          echo "back changed: ${{ steps.changes.outcome == 'failure' || contains(steps.changes.outputs.all_changed_files, 'packages/back') }}" >> $GITHUB_STEP_SUMMARY
          echo "front changed: ${{ steps.changes.outcome == 'failure' || contains(steps.changes.outputs.all_changed_files, 'packages/front') }}" >> $GITHUB_STEP_SUMMARY
