name: Frontend - Build

on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
      targetEnv:
        required: true
        type: string

jobs:
  build:
    name: Build frontend
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          echo "Build ${{ inputs.targetEnv}}!" >> $GITHUB_STEP_SUMMARY
