name: Frontend - Deploy

on:
  workflow_call:
    inputs:
      targetEnv:
        required: true
        type: string

jobs:
  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: |
          echo "Deploy ${{ inputs.targetEnv }}!"
