name: Verify frontend

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ok!" >> output.txt

      - name: Upload build artifacts
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: front-package
          path: output.txt
          retention-days: 1
