name: Initialize

on:
  workflow_call:

jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - id: initialize
        name: Initialize
        uses: ./.github/actions/initialize
