name: Push

on:
  push:

jobs:
  variables:
    name: Variables
    runs-on: ubuntu-latest
    outputs:
      test: ${{ github.ref_name }}
    steps:
      - name: Nothing
        run:

  test:
    name: test
    needs: [variables]
    uses: ./.github/workflows/test.yml
    secrets: inherit
    with:
      test: ${{ needs.variables.outputs.test }}
