name: Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Do it
        uses: actions/github-script@v6
        with:
          script: |
            console.log(${{ fromJSON(github) }});
