name: Test

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Do it
        run: |
          echo "ref: ${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
          echo "ref_name: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
