name: Update staging
run-name: Deploy ${{ github.ref_name }} to staging

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-changes:
    name: Deploy changes
    uses: ./.github/workflows/deploy-changes.yml
    secrets: inherit
    with:
      env: staging

  make-it-slow:
    name: Make it slow
    runs-on: ubuntu-latest
    steps:
      - name: Sleep
        run: sleep 60
