name: Update staging

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-changes:
    name: Deploy changes
    uses: ./.github/workflows/deploy-changes.yml
    secrets: inherit
    with:
      env: staging
      accessKeyIdSecretKey: VRFI_PROD_AWS_ACCESS_KEY_ID
      secretAccessKeySecretKey: VRFI_PROD_AWS_SECRET_ACCESS_KEY
