name: Update staging

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy-changes:
    name: Deploy changes
    uses: ./.github/workflows/deploy-changes.yml
    secrets: inherit
    with:
      env: staging
